global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "report-backend"
    static_configs:
      - targets: ["host.docker.internal:8000"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "postgres"
    static_configs:
      - targets: ["postgres-exporter:9187"]
